# Generated by Django 3.1 on 2020-08-31 22:01

from django.db import migrations

def create_data(apps, schema_editor):
    Categories = apps.get_model('wwealth', 'DataCategories')
    Categories(name="Billionaires").save()
    Categories(name="Billionaire Family").save()


class Migration(migrations.Migration):

    dependencies = [
        ('wwealth', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(create_data),
    ]
