# Generated by Django 3.1 on 2020-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwealth', '0002_wwealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacategories',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Name'),
        ),
    ]
