# Generated by Django 3.1 on 2020-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwealth', '0003_auto_20200901_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacategories',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='marketvalue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='networth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='ranking',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='revenue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheld',
            name='year',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='marketvalue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='networth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='ranking',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='revenue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wealthheldts',
            name='year',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
