# Generated by Django 3.1 on 2020-09-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwealth', '0004_auto_20200907_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wealthheld',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='wealthheldts',
            old_name='categoryId',
            new_name='category',
        ),
    ]
