# Generated by Django 3.1 on 2020-09-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwealth', '0005_auto_20200907_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='wealthheld',
            name='categoryId',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='wwealth.datacategories'),
        ),
        migrations.AddField(
            model_name='wealthheldts',
            name='categoryId',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='wwealth.datacategories'),
        ),
    ]
